Pre-Entrega/Proyecto2/App1/urls.py
from django.urls import path
from App1 import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', views.inicio1, name="inicio"),
    path('inicio', views.inicio1, name="inicio"),
    path('blog/list',views.blogList.as_view(),name='List'),
    path(r'^(?P<pk>\d+)$', views.blogDetalle.as_view(),name='Detail'),
    path(r'^nuevo$', views.blogCreacion.as_view(),name='New'),
    path(r'^editar/(?P<pk>\d+)$',views.blogUpdate.as_view(),name='Edit'),
    path(r'^borrar/(?P<pk>\d+)$',views.blogDelete.as_view(),name='Delete'),
    path('login', views.login_request, name="login"),
    path('register', views.register, name='register'),
    path('logout', LogoutView.as_view(template_name='App1/logout.html'), name = 'logout'),
    path('editarPerfil', views.editarPerfil, name="editarPerfil"), 
    path('agregarAvatar', views.agregarAvatar, name="agregarAvatar"), 
    path('crearBlog', views.crearBlog, name="crearBlog"),
    path('about', views.about, name="about"),
    path('miPerfil', views.miPerfil, name="miPerfil"),
    #blog

    ]

Pre-Entrega/Proyecto2/Proyecto2/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('App1/',include('App1.urls'))
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Pre-Entrega/Proyecto2/App1/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
# Create your models here.

class Dueño(models.Model):
    def __str__(self):
        return f"Nombre: {self.nombre} - Apellido {self.apellido} - E-Mail {self.email}"
    nombre= models.CharField(max_length=30)

    apellido= models.CharField(max_length=30)

    email= models.EmailField()

 

class Blog(models.Model):
    def __str__(self):
        return f"Nombre: {self.titulo} - Apellido {self.subtitulo} - E-Mail {self.contenido} - Profesión {self.autor}"

    titulo = models.CharField(max_length=30)

    subtitulo= models.CharField(max_length=30)

    contenido = models.CharField(max_length=500)

    autor = models.CharField(max_length=40)

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank = True)
    def __str__(self):
        return f"{self.user} - {self.imagen}"
    

Pre-Entrega/Proyecto2/App1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        # Saca los mensajes de ayuda
        help_texts = {k:"" for k in fields}

class blogForms(forms.Form):
    id= forms.IntegerField()
    
    titulo = forms.CharField(max_length=30)

    subtitulo= forms.CharField(max_length=30)

    contenido = forms.CharField(max_length=40)

    autor = forms.CharField(max_length=40)


class UserEditForm(UserCreationForm):
    # Obligatorios
    email = forms.EmailField(label="Ingrese su email:")
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repetir la contraseña', widget=forms.PasswordInput)
    last_name = forms.CharField()
    first_name = forms.CharField()
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'last_name', 'first_name']

class AvatarFormulario(forms.Form):
    #Especificar los campos
    imagen = forms.ImageField(required=True)

Pre-Entrega/Proyecto2/App1/views.py
from django.shortcuts import render
from App1.models import Blog, Avatar
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth import login,logout,authenticate
from App1.forms import blogForms
from django.contrib.auth.decorators import login_required

def inicio1(request):
    return render(request, 'App1/in.html')

def about(request):
    return render(request, 'App1/about.html')
def miPerfil(request):
    return render(request, 'App1/miPerfil.html')

def crearBlog(request):
     if request.method == "POST":
        miFormulario = blogForms(request.POST) # Aqui me llega la informacion del html
        print(miFormulario)
        
        if miFormulario.is_valid:
            informacion = miFormulario.cleaned_data
            blog = Blog(int (informacion['id']), str(informacion['titulo']),str(informacion['subtitulo']),str (informacion['contenido']),str (informacion['autor']))
            blog.save()
            return render(request, "App1/inicio.html")
     else:
        miFormulario =blogForms()
             
     return render(request, "App1/crearBlog.html", {"miFormulario": miFormulario})


def leerBlog(request):
    blogs= Blog.objects.all() # trae a todos los profesores
    contexto= {"blogs": blogs}
    return render(request, "App1/leerBlogs.html",contexto)


from django.views.generic import ListView
class blogList(ListView):
    model = Blog
    template_name='/App1/blog_list.html'

from django.views.generic.detail import DetailView
class blogDetalle(DetailView):
    model= Blog
    template_name= "App1/blog_detalle.html"

from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
class blogCreacion(CreateView):
    model=Blog
    success_url="/App1/blog/list"
    fields=['titulo','subtitulo', 'contenido', 'autor']

from django.views.generic.edit import UpdateView
class blogUpdate(UpdateView):
    model= Blog
    success_url= "/App1/blog/list"
    fields=['contenido']

from django.views.generic.edit import DeleteView

class blogDelete( DeleteView,AuthenticationForm):
    def usuario(request):
        usuario = request.user
    model= Blog
    success_url="/App1/blog/list"
    template_name= "App1/blog_confirm-delete.html"

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():  # Si pasó la validación de Django
            usuario = form.cleaned_data.get('username')
            contrasenia = form.cleaned_data.get('password')
            user = authenticate(username= usuario, password=contrasenia)
            if user is not None:
                login(request, user)
                return render(request, "App1/inicio.html", {"mensaje":f"Bienvenido {usuario}"})
            else:
                return render(request, "App1/inicio.html", {"mensaje":"Datos incorrectos"})
        else:
            return render(request, "App1/inicio.html", {"mensaje":"Formulario erroneo"})
    form = AuthenticationForm()
    return render(request, "App1/login.html", {"form": form})

from App1.forms import UserRegisterForm
def register(request):
      if request.method == 'POST':
            #form = UserCreationForm(request.POST)
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                  username = form.cleaned_data['username']
                  form.save()
                  return render(request,"App1/inicio.html" ,  {"mensaje":"Usuario Creado :)"})
      else:
            #form = UserCreationForm()       
            form = UserRegisterForm()     
      return render(request,"App1/registro.html" ,  {"form":form})

from App1.forms import blogForms , UserRegisterForm, UserEditForm
# Vista de editar el perfil
@login_required
def editarPerfil(request):
    usuario = request.user
    if request.method == 'POST':
        miFormulario = UserEditForm(request.POST)
        if miFormulario.is_valid():
            informacion = miFormulario.cleaned_data
            usuario.email = informacion['email']
            usuario.password1 = informacion['password1']
            usuario.password2 = informacion['password2']
            usuario.last_name = informacion['last_name']
            usuario.first_name = informacion['first_name']
            usuario.save()
            return render(request, "App1/inicio.html")
    else:

        miFormulario = UserEditForm(initial={'email': usuario.email})
    return render(request, "App1/editarPerfil.html", {"miFormulario": miFormulario, "usuario": usuario})

@login_required
def inicio(request):
    avatares= Avatar.objects.filter(user=request.user.id)
    return render(request, 'App1/"inicio".html', {"url":avatares[0].imagen.url})

def some_view(request):
    user_avatar = Avatar.objects.get(user=request.user)
    return render(request, 'padre.html', {'user_avatar': user_avatar})



@login_required
def agregarAvatar(request):
      if request.method == 'POST':
            miFormulario = AvatarFormulario(request.POST, request.FILES) #aquí mellega toda la información del html
            if miFormulario.is_valid():   #Si pasó la validación de Django
                  u = User.objects.get(username=request.user)
                  avatar = Avatar(user=u, imagen=miFormulario.cleaned_data['imagen']) 
                  avatar.save()
                  return render(request, "App1/inicio.html") #Vuelvo al inicio o a donde quieran
      else: 
            miFormulario= AvatarFormulario() #Formulario vacio para construir el html
      return render(request, "App1/agregarAvatar.html", {"miFormulario":miFormulario})

from django.contrib.auth.models import User
from .forms import AvatarFormulario
@login_required
def agregarAvatar(request):
      if request.method == 'POST':
            miFormulario = AvatarFormulario(request.POST, request.FILES) #aquí mellega toda la información del html
            if miFormulario.is_valid():   #Si pasó la validación de Django
                  u = User.objects.get(username=request.user)
                  avatar = Avatar(user=u, imagen=miFormulario.cleaned_data['imagen']) 
                  avatar.save()
                  return render(request, "App1/inicio.html") #Vuelvo al inicio o a donde quieran
      else: 
            miFormulario= AvatarFormulario() #Formulario vacio para construir el html
      return render(request, "App1/agregarAvatar.html", {"miFormulario":miFormulario})

Pre-Entrega/Proyecto2/App1/templates/App1/about.html
<!DOCTYPE html>
<html>
<head>
  <style>
    #mi-elemento-fijo {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      background-color: #f1f1f1;
      padding: 20px;
    }
  </style>
</head>
<body>
  <div id="mi-elemento-fijo">
{% extends "App1/padre.html" %}
  </div>
  {% load static %}

  {% block contenidoQueCambia %}
    <style>
        #contenedor-formulario {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
    </style>

    <div id="contenedor-formulario">
            <!-- Team Section -->
                  <!-- font icons -->
                  <link rel="stylesheet" href="{% static 'App1/assets/vendors/themify-icons/css/themify-icons.css'%}">
                  <!-- Bootstrap + Creative Studio main styles -->
                  <link rel="stylesheet" href="{% static 'App1/assets/css/creative-studio.css' %}">
      <center>
      </style>
          <div class="col-sm-6 col-md-4">
  
              <div class="card text-center mb-4">
                  <img class="card-img-top inset" src="{% static 'App1/assets/imgs/elian.jpg' %}">
                  <div class="card-body">
                      <h6 class="small text-primary font-weight-bold">Alumno</h6>
                      <h5 class="card-title">Elian Bresciani</h5>
                      <p>Me llamo Elian, Tengo 22 años, estudio programacion en la UTN, Este es mi segundo curso de Python, el primero lo hice en Capacitarte.org, lo tome mas para ver si me gustaba lo que es programar y aca estamos.</p>
                      <div class="socials">
                          <a href="https://www.facebook.com/elian.bresciani.3760/"><i class="ti-facebook"></i> </a>
                          <a href="https://github.com/elianbresciani"><i class="ti-github"></i></a>
                          <a href="https://www.instagram.com/elianbresciani/"><i class="ti-instagram"></i></a>
                          <a href="https://twitter.com/Elian_bresciani"><i class="ti-twitter"></i></a>
                      </div>
                  </div>
              </div>
          </div>

  <!-- core  -->
  <script src="assets/vendors/jquery/jquery-3.4.1.js"></script>
  <script src="assets/vendors/bootstrap/bootstrap.bundle.js"></script>
  
  <!-- bootstrap affix -->
  <script src="assets/vendors/bootstrap/bootstrap.affix.js"></script>
  
  <!-- Creative Studio js -->
  <script src="assets/js/creative-studio.js"></script>
    </div>
  </body>
  </html>
  <!--Aquí va lo que cambia, y lo asociado a está vista :) -->    
  {% endblock %}

Pre-Entrega/Proyecto2/App1/templates/App1/agregarAvatar.html
<!DOCTYPE html>
<html>
<head>
  <style>
    #mi-elemento-fijo {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      background-color: #f1f1f1;
      padding: 20px;
    }
  </style>
</head>
<body>
  <div id="mi-elemento-fijo">
    {% extends "App1/padre.html" %}
  </div>
    {% block contenidoQueCambia %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <title>Cargar Avatar</title>
</head>
<style>
    #contenedor-formulario {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh; /* Ajusta la altura según tus necesidades */
    }
  </style>
<body>
<div id="contenedor-formulario">
        <!-- Tu formulario aquí -->
    <h3>Cargar Avatar</h3>
    <h3>...</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ miFormulario.as_p}}
            <input type="submit" value="Actualizar">
        </form>
</div>
</body>
</html>
{% endblock %}

Pre-Entrega/Proyecto2/App1/templates/App1/blog_confirm-delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form method="post">{% csrf_token %}
        ¿Estas seguro de que deseas borrar el blog "{{ object }}"?
        <input type="submit" value="Submit">
    </form>
</body>
</html>

Pre-Entrega/Proyecto2/App1/templates/App1/blog_detalle.html
<!DOCTYPE html>
<html>
<head>
  <style>
    #mi-elemento-fijo {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      background-color: #f1f1f1;
      padding: 20px;
    }
  </style>
</head>
<body>
  <div id="mi-elemento-fijo">
    {% extends "App1/padre.html" %}
  </div>
    {% block contenidoQueCambia %}
    
    <style>
        #contenedor-lista {
          padding-top: 90px; /* O utiliza margin-top: 20px; según tus necesidades */
        }
    </style>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="contenedor-lista">
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Document</title>
        </head>
        <body>
            <p>titulo del blog: <i>{{ blog.titulo }}</i></p>
            <p>subtitulo: <i>{{ blog.subtitulo }}</i></p>
            <p>contenido: <i>{{ blog.contenido }}</i></p>
            <p>autor: {{ blog.autor }}</p>
                <a href="{%url 'List' %}">Regresar</a>
                {% if request.user.username == blog.autor %}
                    <a href="{% url 'Delete' blog.id %}">Borrar</a>
                {% endif %}
        </body>
        </html>
    </ul>
    
</body>
</html>
{% endblock %}

Pre-Entrega/Proyecto2/App1/templates/App1/blog_form.html
<!DOCTYPE html>
<html>
<head>
  <style>
    #mi-elemento-fijo {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      background-color: #f1f1f1;
      padding: 20px;
    }
  </style>
</head>
<body>
  <div id="mi-elemento-fijo">
    {% extends "App1/padre.html" %}
  </div>
    {% block contenidoQueCambia %}
    
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario - Agregar Curso</title>
</head>
<style>
    #contenedor-formulario {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh; /* Ajusta la altura según tus necesidades */
    }
  </style>
<body>
<div id="contenedor-formulario">
        <!-- Tu formulario aquí -->

        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Document</title>
        </head>
        <body>
            <form method="post">
                {% csrf_token %} 
                {{"contenido actual:"}}
                {{ blog.contenido }}{{ form.as_p }}
        
                <input type="submit" value="Enviar" />
            </form>
        </body>
        </html>
        
        <!DOCTYPE html>
        <html>
        <head>
</div>
</html>
    {% endblock %}

Pre-Entrega/Proyecto2/App1/templates/App1/dueñoFormulario.html
    <!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    <h1>Formulario - Editar Profesor</h1>
    
    {% if miFormulario.errors %}

    <p style="color: red;"> Están mal los datos, revisar</p>

    {% endif %}

    <form action="" method="POST">{% csrf_token %}

        <!-- Acá está la magia de Django-->
        
        <table>

            {{ miFormulario.as_table }}

        </table>

        <input type="submit", value="Enviar">

    </form>

Pre-Entrega/Proyecto2/App1/templates/App1/inicio.html
{% extends "App1/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
        <!-- Page Header -->
        <header class="header">
            <div class="overlay">

                <h1 class="title"> 
                    <div class="text-center">
                        {% if request.user.is_authenticated %}
                                {% with avatares=request.user.avatar_set.all %}
                                    {% if avatares %}
                                        <img height="50px" src="{{avatares.0.imagen.url}}">
                                    {% endif %}
                                    <p class="text-muted small mb-4 mb-lg-0">Bienvenido {{ request.user.username }}</p>
                                {% endwith %}
                            {% endif %}
                        <h3> Esta es mi primera pagina web!</h3>
                    </div>
                </h1>                  
            </div>      
        </header>
        
    <!-- Team Section -->

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
    </div>
</div>
</div>
<!-- end of modal -->

<!-- Blog Section -->


<!-- core  -->
<script src="assets/vendors/jquery/jquery-3.4.1.js"></script>
<script src="assets/vendors/bootstrap/bootstrap.bundle.js"></script>

<!-- bootstrap affix -->
<script src="assets/vendors/bootstrap/bootstrap.affix.js"></script>

<!-- Creative Studio js -->
<script src="assets/js/creative-studio.js"></script>

</body>
</html>
<!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    {% if mensaje %}
        <p>{{ mensaje }}</p>
    {% endif %}

    {% endblock %}

Pre-Entrega/Proyecto2/App1/templates/App1/miPerfil.html
<!DOCTYPE html>
<html>
<head>
  <style>
    #mi-elemento-fijo {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      background-color: #f1f1f1;
      padding: 20px;
    }
  </style>
</head>
<body>
  <div id="mi-elemento-fijo">
    {% extends "App1/padre.html" %}
  </div>
    {% load static %}
    {% block contenidoQueCambia %}
    
    <style>
        #contenedor-lista {
          padding-top: 60px; /* O utiliza margin-top: 20px; según tus necesidades */
        }
    </style>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="contenedor-lista">
        <div id="contenedor-formulario">
            <!-- Team Section -->
                  <!-- font icons -->
                  <link rel="stylesheet" href="{% static 'App1/assets/vendors/themify-icons/css/themify-icons.css'%}">
                  <!-- Bootstrap + Creative Studio main styles -->
                  <link rel="stylesheet" href="{% static 'App1/assets/css/creative-studio.css' %}">
      <center>
      </style>
          <div class="col-sm-6 col-md-4">
  
              <div class="card text-center mb-4">
                  <div class="card-body">
                      <h6 class="small text-primary font-weight-bold">Alumno</h6>
                {% if request.user.is_authenticated %}
                      {% with avatares=request.user.avatar_set.all %}
                          {% if avatares %}
                            <img class="card-img-top inset" src="{{avatares.0.imagen.url}}">
                          {% endif %}
                            <p> </p>
                            <a class="navbar-brand" href="#nada">-------------------------------------------</a>
                            <p class="text-muted small mb-4 mb-lg-0">{{ request.user.username }}</p>
                            <p class="text-muted small mb-4 mb-lg-0">{{ request.user.email }}</p>
                            <p class="text-muted small mb-4 mb-lg-0">{{ request.user.first_name }}</p>
                            <p class="text-muted small mb-4 mb-lg-0">{{ request.user.last_name }}</p>
                      {% endwith %}
                {%endif%}
                      <li class="nav-item">
                        <a class="navbar-brand" href="{% url 'editarPerfil' %}">Editar Perfil</a>
                    </li>
                  </div>
              </div>
          </div>

  <!-- core  -->
  <script src="assets/vendors/jquery/jquery-3.4.1.js"></script>
  <script src="assets/vendors/bootstrap/bootstrap.bundle.js"></script>
  
  <!-- bootstrap affix -->
  <script src="assets/vendors/bootstrap/bootstrap.affix.js"></script>
  
  <!-- Creative Studio js -->
  <script src="assets/js/creative-studio.js"></script>
    </div>
  </body>
  </html>
</body>
</html>
{% endblock %}

Pre-Entrega/Proyecto2/App1/templates/App1/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <meta name="description" content="Start your development with Creative Studio landing page.">
            <meta name="author" content="Devcrud">
            <title>Creative Studio | Free Bootstrap 4.3.x template</title>
        
            <!-- font icons -->
            <link rel="stylesheet" href="{% static 'App1/assets/vendors/themify-icons/css/themify-icons.css'%}">
            <!-- Bootstrap + Creative Studio main styles -->
            <link rel="stylesheet" href="{% static 'App1/assets/css/creative-studio.css' %}">
            <!----fondo--->
            <body background="{% static 'App1/assets/imgs/header.png' %}"></body>
        </head>
        <body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">
            
            <!-- Page Navigation -->
            <nav class="navbar custom-navbar navbar-expand-lg navbar-dark" data-spy="affix" data-offset-top="20">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'inicio' %}">
                        <img src="{% static 'App1/assets/imgs/logo.png' %}">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="navbar-brand" href="{% url 'inicio' %}">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" href="{% url 'about' %}">About</a>
                            </li>
                            {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="navbar-brand" href="{% url 'crearBlog' %}">Crear Blog</a>
                            </li>
                            {% endif %}
                            {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="navbar-brand" href="{% url 'List' %}">Blogs</a>
                            </li>
                            {% endif %}
                            {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="navbar-brand" href="{% url 'agregarAvatar' %}">Cambiar Avatar</a>
                            </li>
                            {% endif %}
                            {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="navbar-brand" href="{% url 'miPerfil' %}">Perfil</a>
                            </li>
                            {% endif %}
                            {% if request.user.is_authenticated %}
                                    {% with avatares=request.user.avatar_set.all %}
                                        {% if avatares %}
                                            <img height="50px" src="{{avatares.0.imagen.url}}">
                                        {% endif %}
                                        <p class="text-muted small mb-4 mb-lg-0">{{ request.user.username }}</p>
                                    {% endwith %}
                                {% else %}
                                    <a class="btn btn-primary" href="{% url 'login' %}">iniciar sesion</a>
                                    <a class="btn btn-primary" href="{% url 'register' %}">Registrarse</a>
                                {% endif %}
                            {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link btn btn-primary btn-sm ml-lg-3" href="{% url 'logout' %}">Logout</a>
                             </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Of Page Navigation -->

            <!-- core  -->
    <script src="assets/vendors/jquery/jquery-3.4.1.js"></script>
    <script src="assets/vendors/bootstrap/bootstrap.bundle.js"></script>

        <!-- bootstrap affix -->
    <script src="assets/vendors/bootstrap/bootstrap.affix.js"></script>

        <!-- Creative Studio js -->
    <script src="assets/js/creative-studio.js"></script>
</body>
</html>

        {% block contenidoQueCambia %}

        {% endblock %}